title: "Rune's Blog"
description: "Outlet for sharing thoughts with the world."
url: "https://codebolt.github.io" # the full URL of your site
baseurl: "" # no subpath for username.github.io
theme: minima
paginate: 5
