title: "Rune's Blog"
description: "My personal outlet for sharing stuff with the world."
url: "https://codebolt.github.io"
baseurl: "" # no subpath for username.github.io
theme: minima
google_analytics: "G-BCELR7DFQ3"
paginate: 5
timezone: Europe/Oslo
